### ISSUE TITLE
Fix UI

### ISSUE THREAD

**Issue by johndcna** [johndcna/LOPweb#1]
-matabunan ang text box ig login sa logo
-ang display name ig login dako kaayog font d masud sa screen sa upper left
-ang background sa login ug katong mga plain background sa main html ask ko if final na to sya?

**Comment by Shufreezy** [comment]
Ah. Dapat responsive. Ako gi test 1920 ok raman. Ge fix everything first thing in the morning

**Comment by Shufreezy** [comment]
I don't know about the design sa sulod though pero ang background di pato final

**Comment by johndcna** [comment]
ok2 ikaw bahala sa pag design sa ui ang structure sa mga div ok na mana
